# Generated by Django 5.2.17 on 2026-09-22 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='grievances__name_5ae855_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('stores', models.ManyToManyField(blank=True, related_name='user_profiles', to='grievances.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open_date', models.DateField()),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('enquiry_received_by', models.CharField(max_length=255)),
                ('enquiry_details', models.TextField()),
                ('first_level', models.CharField(blank=True, max_length=255)),
                ('second_level', models.CharField(blank=True, max_length=255)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('period_days', models.IntegerField(blank=True, help_text='Number of days taken to close', null=True)),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('hold', 'Hold'), ('extension', 'Extension'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grievances', to=settings.AUTH_USER_MODEL)),
                ('enquiry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievances.enquirytype')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievances.store')),
            ],
            options={
                'ordering': ['-open_date'],
                'indexes': [models.Index(fields=['emp_id'], name='grievances__emp_id_64b56d_idx'), models.Index(fields=['open_date'], name='grievances__open_da_0d5e24_idx'), models.Index(fields=['current_status'], name='grievances__current_eb22ca_idx')],
            },
        ),
    ]
