# Generated by Django 5.2.17 on 2026-09-22 05:37

import django.db.models.deletion
from django.db import migrations, models


def map_roles_to_fk(apps, schema_editor):
    UserProfile = apps.get_model('grievances', 'UserProfile')
    Role = apps.get_model('grievances', 'Role')
    
    # Pre-create roles
    admin_role, _ = Role.objects.get_or_create(name='admin', defaults={'description': 'Administrator'})
    staff_role, _ = Role.objects.get_or_create(name='staff', defaults={'description': 'Staff'})
    user_role, _ = Role.objects.get_or_create(name='user', defaults={'description': 'User'})
    
    # Update all profiles
    for profile in UserProfile.objects.all():
        if profile.role == 'admin':
            profile.role = admin_role.id
        elif profile.role == 'staff':
            profile.role = staff_role.id
        elif profile.role == 'user':
            profile.role = user_role.id
        else:
            profile.role = user_role.id # fallback
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(map_roles_to_fk),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='grievances.role'),
        ),
    ]
