# Generated by Django 5.2.17 on 2026-09-22 05:44

from django.db import migrations


def consolidate_to_hr(apps, schema_editor):
    UserProfile = apps.get_model('grievances', 'UserProfile')
    Role = apps.get_model('grievances', 'Role')
    
    # Create HR role if it doesn't exist
    hr_role, _ = Role.objects.get_or_create(name='hr', defaults={'description': 'Human Resources'})
    
    # Update profiles to use HR role if they aren't admin
    admin_role = Role.objects.filter(name='admin').first()
    
    for profile in UserProfile.objects.all():
        if profile.role != admin_role:
            profile.role = hr_role
            profile.save()

    # Optional: Delete old unused roles (staff, user)
    Role.objects.filter(name__in=['staff', 'user']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.RunPython(consolidate_to_hr),
    ]
