# Generated by Django 5.2.17 on 2026-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_auto_20260922_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='closing_reason',
            field=models.TextField(blank=True, verbose_name='Closing Reason / Resolution Summary'),
        ),
    ]
