# Generated by Django 5.2.17 on 2026-09-28 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0003_auto_20260922_1114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.CharField(blank=True, max_length=50, verbose_name='Month')),
                ('breakfast_menu', models.CharField(blank=True, max_length=500, verbose_name='Breakfast Menu')),
                ('breakfast_received_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Breakfast Received (kg)')),
                ('breakfast_wastage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Breakfast Wastage (kg)')),
                ('breakfast_shortage', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10, verbose_name='Breakfast Shortage')),
                ('breakfast_shortage_count', models.IntegerField(blank=True, null=True, verbose_name='Breakfast Shortage Count')),
                ('breakfast_review', models.CharField(blank=True, choices=[('not_good', 'Not Good'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, verbose_name='Breakfast Review')),
                ('breakfast_remarks', models.TextField(blank=True, verbose_name='Breakfast Remarks')),
                ('lunch_menu', models.CharField(blank=True, max_length=500, verbose_name='Lunch Menu')),
                ('lunch_received_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lunch Received (kg)')),
                ('lunch_wastage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lunch Wastage (kg)')),
                ('lunch_shortage', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10, verbose_name='Lunch Shortage')),
                ('lunch_shortage_count', models.IntegerField(blank=True, null=True, verbose_name='Lunch Shortage Count')),
                ('lunch_review', models.CharField(blank=True, choices=[('not_good', 'Not Good'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, verbose_name='Lunch Review')),
                ('lunch_remarks', models.TextField(blank=True, verbose_name='Lunch Remarks')),
                ('dinner_menu', models.CharField(blank=True, max_length=500, verbose_name='Dinner Menu')),
                ('dinner_received_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dinner Received (kg)')),
                ('dinner_wastage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dinner Wastage (kg)')),
                ('dinner_shortage', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10, verbose_name='Dinner Shortage')),
                ('dinner_shortage_count', models.IntegerField(blank=True, null=True, verbose_name='Dinner Shortage Count')),
                ('dinner_review', models.CharField(blank=True, choices=[('not_good', 'Not Good'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, verbose_name='Dinner Review')),
                ('dinner_remarks', models.TextField(blank=True, verbose_name='Dinner Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_waste_entries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_waste_entries', to='grievances.store', verbose_name='Store Name')),
            ],
            options={
                'verbose_name': 'Food Waste Entry',
                'verbose_name_plural': 'Food Waste Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='food_waste__date_b46230_idx'), models.Index(fields=['store', 'date'], name='food_waste__store_i_d95b8c_idx')],
            },
        ),
    ]
