# Generated by Django 5.2.17 on 2026-09-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwasteentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='September', max_length=20, verbose_name='Month'),
        ),
        migrations.CreateModel(
            name='FoodWasteStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Store Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Waste Store',
                'verbose_name_plural': 'Food Waste Stores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='food_waste__name_60799a_idx')],
            },
        ),
        migrations.AlterField(
            model_name='foodwasteentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_waste_entries', to='food_waste.foodwastestore', verbose_name='Store Name'),
        ),
    ]
