# Generated by Django 5.2.17 on 2026-09-28 06:46

import food_waste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_waste', '0002_alter_foodwasteentry_month_foodwastestore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwasteentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=food_waste.models.get_current_month, max_length=20, verbose_name='Month'),
        ),
    ]
